//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolutionLocalization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolutionLocalization.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read &apos;{0}&apos; file (exception: {1}).
        /// </summary>
        internal static string CannotReadFileDetailException {
            get {
                return ResourceManager.GetString("CannotReadFileDetailException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking translations for &apos;{0}&apos;....
        /// </summary>
        internal static string CheckingTranslation {
            get {
                return ResourceManager.GetString("CheckingTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Spreadsheet....
        /// </summary>
        internal static string CreatingSpreadsheet {
            get {
                return ResourceManager.GetString("CreatingSpreadsheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Xml....
        /// </summary>
        internal static string CreatingXml {
            get {
                return ResourceManager.GetString("CreatingXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading data from {0}..
        /// </summary>
        internal static string DownloadingDataFrom {
            get {
                return ResourceManager.GetString("DownloadingDataFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download status: {0}%..
        /// </summary>
        internal static string DownloadStatus {
            get {
                return ResourceManager.GetString("DownloadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occured reading {0}.
        /// </summary>
        internal static string ErrorReadingFile {
            get {
                return ResourceManager.GetString("ErrorReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occured reading {0} (Exception: {1}).
        /// </summary>
        internal static string ErrorReadingFileDetailException {
            get {
                return ResourceManager.GetString("ErrorReadingFileDetailException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XLS document has no language information..
        /// </summary>
        internal static string IgnoreXLSGenerationNoLanguage {
            get {
                return ResourceManager.GetString("IgnoreXLSGenerationNoLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore generation, no-translations defined.
        /// </summary>
        internal static string IgnoreXLSGenerationNoTranslations {
            get {
                return ResourceManager.GetString("IgnoreXLSGenerationNoTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt; Exception: {0}.
        /// </summary>
        internal static string InfoExceptionDetail {
            get {
                return ResourceManager.GetString("InfoExceptionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt; Info: looking only for &lt;control&gt;.Text expressions..
        /// </summary>
        internal static string InfoReadingControlText {
            get {
                return ResourceManager.GetString("InfoReadingControlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring translation for FILE:{0}, KEY:{1} - obsolete.
        /// </summary>
        internal static string IntegrityIgnoringObsoleteTranslation {
            get {
                return ResourceManager.GetString("IntegrityIgnoringObsoleteTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring translation for FILE:{0}, KEY:{1} - original text has changed.
        /// </summary>
        internal static string IntegrityIgnoringOriginalChangedTranslation {
            get {
                return ResourceManager.GetString("IntegrityIgnoringOriginalChangedTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load file &apos;{1}&apos; thus, message integrity validation is disabled (exception: {0}).
        /// </summary>
        internal static string MessageIntegrityValidationDisabled {
            get {
                return ResourceManager.GetString("MessageIntegrityValidationDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error: {0}.
        /// </summary>
        internal static string OutputError {
            get {
                return ResourceManager.GetString("OutputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warning: {0}.
        /// </summary>
        internal static string OutputWarning {
            get {
                return ResourceManager.GetString("OutputWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading {0}.
        /// </summary>
        internal static string ReadingFile {
            get {
                return ResourceManager.GetString("ReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start resx generation for culture {0}..
        /// </summary>
        internal static string StartCultureResxGeneration {
            get {
                return ResourceManager.GetString("StartCultureResxGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully generated..
        /// </summary>
        internal static string XLSGenerationSuccess {
            get {
                return ResourceManager.GetString("XLSGenerationSuccess", resourceCulture);
            }
        }
    }
}
